image: nicka101/magento2

variables:
  VENDOR_NAME: SITC
  PACKAGE_NAME: Sinchimport

stages:
  - test
  - package

marketplace-eqp:
  stage: test
  script:
  - cd /magento2/eqp
  - vendor/bin/phpcs --standard=MEQP2 --severity=10 --colors -p $CI_PROJECT_DIR

copy-paste-detector:
  stage: test
  script:
  - cd /magento2/data
  - vendor/bin/phpcpd $CI_PROJECT_DIR || true

unused-code-detector:
  stage: test
  script:
  - cd /magento2/data
  - vendor/bin/phpmd $CI_PROJECT_DIR text unusedcode

package:
  stage: package
  script:
  - cd $CI_PROJECT_DIR
  - zip -r ${VENDOR_NAME}_${PACKAGE_NAME}-${CI_COMMIT_REF_NAME}.zip . -x './.git/*'
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
  only:
    - tags

